### ISSUE TITLE
there's no public directory

### ISSUE THREAD

**Issue by alagoroChapela** [wintercms/docs#156]
There's no /public directory, and install doesn't create it, so composer instalation doesn't work "out of the box"

**Comment by bennothommo** [comment]
By default there's no public directory, but the install should still work out of the box, as the public directory is not a requirement (although it is good practice).

If you wish to have a public directory to point the web server to, you simply need to run `php artisan winter:mirror public/` after installation.

See: https://wintercms.com/docs/v1.2/docs/setup/configuration#using-a-public-folder

**Comment by LukeTowers** [comment]
See https://wintercms.com/docs/v1.2/docs/console/setup-maintenance#mirror-public-files. It's a holdover from the original platform being designed to be installed via a wordpress-like web installer that there isn't a public folder by default as on shared hosts you'd typically be installing the project into the "public" folder already.

My personal recommendation and own process has always been to use a public folder though; and the example project now includes that as well: https://github.com/wintercms/wn-blizzard.wintercms.com-site/commit/a5395948b2c54cf27518415a5cdc277ef5c557da

**Comment by LukeTowers** [comment]
@bennothommo too quick on the draw, you beat me to it 😂

**Comment by bennothommo** [comment]
GitHub really needs one of those "Someone is typing a comment..." notifications like Facebook.
