### ISSUE TITLE
Width of table column.

### ISSUE THREAD

**Issue by WebVPF** [wintercms/docs#18]
Take a look at width of first column of table.

Page: https://wintercms.com/docs/themes/development#theme-information

Google Chrome Browser:

![2021-05-29_182852](https://user-images.githubusercontent.com/61043464/120075974-2d309a80-c0ac-11eb-9882-d0fe93ff7bb5.jpg)

**Comment by LukeTowers** [comment]
Deploying the fix now, thanks for the report!
