### ISSUE TITLE
Missing Information on "testing" documentation page

### ISSUE THREAD

**Issue by samcoppock** [wintercms/docs#188]
On this page 

https://wintercms.com/docs/v1.2/docs/setup/upgrade-guide#laravel-packages
 
It mentions that 
"Unit testing should now be conducted using the php artisan winter:test command, as opposed to running unit tests directly on phpunit. This ensures that the correct bootstrap is used, as well as the necessary environment configuration is created."
 
On this page
https://wintercms.com/docs/v1.2/docs/console/utilities
 
It documents the winter:test command in depth
 
however on this page
"https://wintercms.com/docs/v1.2/docs/plugin/unit-testing"
 
The fact that you are now supposed to use winter:test instead of phpunit is not mentioned.
 
I think it should be mentioned on the 3rd page because that is the one which appears in the left hand menu, it is the one that explains how to setup unit tests in winter, is the one that appears in google ( for me anyway ),  and is the closest thing to a direct piece of documentation for unit testing in Winter.
yet it makes no mention of the fact that you must use winter:test to run tests
 
Aditionally running 'phpunit' when using "\System\Tests\Bootstrap\TestCase" does indeed cause an error but you only get an error message if specific settings are turned on in php.ini, even with it turned on the error only tells you that "\System\Tests\Bootstrap\TestCase" could not be found which is not at all helpful.

the first page is a upgrade guide and the second page is an more indepth guide regarding a specific function so someone using the documentation to setup unit tests would not know to look there unless they happened to be in the process of upgrading winter.

**Comment by LukeTowers** [comment]
@WebVPF would you like to take a stab at a PR to improve the plugin unit testing docs?

**Comment by bennothommo** [comment]
Arguably, the https://wintercms.com/docs/v1.2/docs/plugin/unit-testing page is specifically documenting the *creation* of unit tests in the context of a plugin, but I agree that some mention of the `winter:test` command in there should be added.

**Comment by bennothommo** [comment]
Fixed by https://github.com/wintercms/docs/commit/562c0cc93212e898d76e308908bba7fc66ecdd8f
