### ISSUE TITLE
Previous documentation versions

### ISSUE THREAD

**Issue by samcoppock** [wintercms/docs#189]
On the main documentation page 

ie

https://wintercms.com/docs/v1.2/docs/setup/installation

there is a version dropdown in the top left.
however no options other that 1.2 are available

**Comment by LukeTowers** [comment]
What's the status of the new version of that selector @bennothommo?

**Comment by bennothommo** [comment]
@LukeTowers the changes on the staging site need to be merged in first, but theoretically all that's required is for us to split off the docs into another branch for the older versions and add some additional deployment triggers to re-render the older docs.

**Comment by LukeTowers** [comment]
This has been merged and deployed: https://wintercms.com/docs
