### ISSUE TITLE
Docs search feature on the API section returns SQL errors

### ISSUE THREAD

**Issue by nmiyazaki-chapleau** [wintercms/docs#192]
Currently, the search function is returning an SQL error: 
![image](https://github.com/wintercms/docs/assets/104367522/e3127145-3df4-4d2d-9198-85b1cb546cba)
I do not know what is causing this, but in any case something must have gone very wrong to display an SQL error in production.

The other endpoints for Docs, Markup and UI are working fine.

**Comment by bennothommo** [comment]
Duplicate of https://github.com/wintercms/wn-search-plugin/issues/5
