### ISSUE TITLE
Example codes not compatible with PSR2

### ISSUE THREAD

**Issue by damsfx** [wintercms/docs#212]
In PSR2, closures **MUST** be declared with a space after the function keyword,
https://www.php-fig.org/psr/psr-2/#6-closures

This is not really the case in some of the examples of Winter's documentation.
E.g. : https://wintercms.com/docs/v1.2/docs/database/model#property-methods
```php
\Backend\Models\User::extend(function($model) {
    // ...
});
```
Every time I copy/paste a code example, I end up with PHPCS producing an error.

Do you believe that the documentation examples should be PSR2-compliant?

**Comment by LukeTowers** [comment]
Yes, PRs welcome :)
