### ISSUE TITLE
Nginx config is not aware about web-installation files

### ISSUE THREAD

**Issue by u07** [wintercms/docs#79]
Hi! I think, [the manual](https://wintercms.com/docs/setup/configuration) for nginx should be updated in order to allow execution of install.php and other /install scripts.

**Comment by u07** [comment]
I mean, there must be something like this:

```
		# Install: delete when done
		location ~ \.php$ { 	    
			include fastcgi_params;
	        	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	        	#fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
			fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
		}		
		location ~ \install { 	    
			try_files $uri $uri/ =404;
		}
```

**Comment by LukeTowers** [comment]
Feel free to submit a PR to add a section to https://wintercms.com/docs/setup/installation#web-based-installation if you'd like.
