### ISSUE TITLE
Helpers section does not contain any helpers

### ISSUE THREAD

**Issue by der-On** [wintercms/docs#8]
As a user I want to see the available helper functions

## Current behaviour

- I open the Helpers section in the left hand menu
- The main content area just displays a single paragraph but no helpers

## Expected behaviour

- I open the Helpers section in the left hand menu
- The main content area displays all available helpers

**Comment by LukeTowers** [comment]
Seems to work fine for me? https://octobercms.com/docs/services/helpers. I tested on the new website too and it works fine there; so maybe it's a glitch on the October website.

**Comment by der-On** [comment]
@LukeTowers Awww. I'm totally sorry, this was meant for the docs plugin. I will close and reopen the issue there.
