### ISSUE TITLE
[v1.2] PHPUnit.xml file from docs does not work

### ISSUE THREAD

**Issue by ericp-mrel** [wintercms/docs#88]
### Winter CMS Build

1.2

### PHP Version

8.0

### Database engine

No database

### Issue description

`php artisan winter:test` command throws an error when run with the phpunit.xml file from the [docs](https://wintercms.com/docs/help/unit-testing#testing-plugins) in a brand new plugin.

```bash
Cannot open file "[truncated]/plugins/bdx/toolbox/../../../tests/bootstrap.php".
```

### Steps to replicate

1. Create new Winter CMS project
2. Create new plugin (`php artisan create:plugin`)
3. Create phpunit.xml file in plugin directory, contents from [docs](https://wintercms.com/docs/help/unit-testing#testing-plugins)
4. Run `php artisan winter:test`

### Workaround

Replace the bootstrap="" line with the following contents. (Not sure if this is actually correct, but it works).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="../../../modules/system/tests/bootstrap/app.php"
         colors="true"
    ...
```

**Comment by bennothommo** [comment]
@ericp-mrel I've pushed a fix to Winter 1.2 which automatically adds the correct bootstrap file when using the `php artisan winter:test` command - https://github.com/wintercms/winter/commit/43468b3b9fea6919f17e649dc3604cc1ee1b056b. This should be available by the next Winter 1.2 version, or you can get it now by checking out the `develop` branch of Winter.

If you want to test your plugin with Winter 1.1, you can keep the bootstrap path as it was originally, as this fix will overwrite it for Winter 1.2 only. I've added some details to our upgrade guide which should help you make the tests work on both versions: https://github.com/wintercms/meta/blob/master/l9-upgrade-notes.md#upgrade-unit-testing
